script:
  arret_alarme:
    sequence:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
      data:
        code: "yourSecretPassword"
        
  allume_alarme:
    sequence:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.home_alarm
      data:
        code: "yourSecretPassword"
        
        
  allume_alarme_away:
    sequence:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm
      data:
        code: "yourSecretPassword"
        

automation:
  - alias: arret_alarme_auto
    trigger:
      - platform: time
        at: '07:00:00'
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
    action:
      service: script.turn_on
      entity_id: script.arret_alarme
      
  - alias: allumage_auto_alarme
    trigger:
      - platform: time
        at: '21:00:00'
    action:
      service: script.turn_on
      entity_id: script.allume_alarme
      
  
  - alias: RFID_Alarm_On_Total
    trigger:
       - platform: mqtt
         topic: "home/rfid"
    condition:
        condition: and
        conditions:
          - condition: template
            value_template: '{{ trigger.payload == "yourSecretCardUid" or trigger.payload == "yourSecretCardUid2" }}'
          - condition: state
            entity_id: alarm_control_panel.home_alarm
            state: disarmed
    action:
       - service: script.turn_on
         entity_id: script.allume_alarme_away
          
          
  - alias: RFID_Alarm_off_general
    trigger:
      platform: mqtt
      topic: "home/rfid"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ trigger.payload == "yourSecretCardUid" or trigger.payload == "yourSecretCardUid2"}}'
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: armed_home
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: armed_away
            - condition: state
              entity_id: alarm_control_panel.home_alarm
              state: pending
     
    action:
      - service: notify.notif_seb
        data:
          title: "Alarme sur Off"
          message: "RFID -> Alarm off!"
      - service: script.turn_on
        entity_id: script.arret_alarme




